### ISSUE TITLE
Intermittent error when visiting styleguide in dev mode & 503 error on Heroku

### ISSUE THREAD

**Issue by chrisgriffin** [dewski/kss-rails#29]
I've set up kss-rails per instructions spelled out here but on my local machine I sometimes get these:

`undefined method `styleguide_block' for #<#<Class:0x007fc3d32975b8>:0x007fc3d3296208>`

This error didn't occur all the time, usually only after a long interval between a browser refresh. I would usually restart the local server (pow) and the rails app and it would work again.

Now I'm trying to get the styleguide to work on heroku, and I'm getting a 503 error (Connection closed without response) when visiting `/styleguide`. My guess is the 2 issues are related but I'm not certain.

Here's the intermittent error I get locally:

![screen shot 2014-01-08 at 5 27 55 pm](https://f.cloud.github.com/assets/390/1874455/1c4d6688-78d1-11e3-9ac7-7f9ab5cc534a.png)

stack trace:

```
app/views/kss/home/index.html.erb:5:in `_app_views_kss_home_index_html_erb___4220899073351897285_70239519024100'
actionpack (4.0.0) lib/action_view/template.rb:143:in `block in render'
activesupport (4.0.0) lib/active_support/notifications.rb:161:in `instrument'
actionpack (4.0.0) lib/action_view/template.rb:141:in `render'
actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
actionpack (4.0.0) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.0) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'
actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (4.0.0) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionpack (4.0.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionpack (4.0.0) lib/action_view/renderer/renderer.rb:23:in `render'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:127:in `_render_template'
actionpack (4.0.0) lib/action_controller/metal/streaming.rb:219:in `_render_template'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:120:in `render_to_body'
actionpack (4.0.0) lib/action_controller/metal/rendering.rb:33:in `render_to_body'
actionpack (4.0.0) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:97:in `render'
actionpack (4.0.0) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.0.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/stefansundin/.rbenv/versions/2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
activesupport (4.0.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.0.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.0.0) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.0) lib/active_support/callbacks.rb:393:in `_run__2938693327759677716__process_action__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (4.0.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.0.0) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.0) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
railties (4.0.0) lib/rails/engine.rb:511:in `call'
railties (4.0.0) lib/rails/railtie/configurable.rb:30:in `method_missing'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.0) lib/action_dispatch/routing/route_set.rb:655:in `call'
omniauth (1.1.0) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.0) lib/omniauth/strategy.rb:157:in `call'
omniauth (1.1.0) lib/omniauth/builder.rb:48:in `call'
http_accept_language (2.0.0) lib/http_accept_language/middleware.rb:13:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
activerecord (4.0.0) lib/active_record/migration.rb:369:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.0.0) lib/active_support/callbacks.rb:373:in `_run__949714332256560162__call__callbacks'
activesupport (4.0.0) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
config/initializers/quiet_assets.rb:11:in `call_with_quiet_assets'
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
railties (4.0.0) lib/rails/engine.rb:511:in `call'
railties (4.0.0) lib/rails/application.rb:97:in `call'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:145:in `handle'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:99:in `rescue in block (2 levels) in start'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:96:in `block (2 levels) in start'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:86:in `each'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:86:in `block in start'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:66:in `loop'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:66:in `start'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:13:in `run'
/Users/stefansundin/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/bin/nack_worker:4:in `<main>'
```

heroku error (omitted URL):

sidenote: I think the cache error might be an entirely different issue to do with sass 3.3.0.rc.2. KSS works locally for me with this version of sass.

```
2014-01-09T01:58:41.399404+00:00 app[web.1]: Started GET "/styleguide" for 76.79.149.70 at 2014-01-09 01:58:41 +0000
2014-01-09T01:58:41.403097+00:00 app[web.1]: Processing by Kss::HomeController#index as HTML
2014-01-09T01:58:41.434202+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (1.3ms)
2014-01-09T01:58:41.434521+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (0.1ms)
2014-01-09T01:58:41.434834+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (0.2ms)
2014-01-09T01:58:41.436397+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (1.4ms)
2014-01-09T01:58:41.437858+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (1.2ms)
2014-01-09T01:58:41.439242+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (1.2ms)
2014-01-09T01:58:41.439793+00:00 app[web.1]:   Rendered kss/shared/_styleguide_block.erb (0.4ms)
2014-01-09T01:58:41.439881+00:00 app[web.1]:   Rendered kss/home/index.html.erb within layouts/kss/application (33.2ms)
2014-01-09T01:58:41.580682+00:00 app[web.1]: Warning. Error encountered while saving cache 208d024c3387f3aaad21f7177290d756a4e172da/color_swatches.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:41.580682+00:00 app[web.1]: 
2014-01-09T01:58:41.586487+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_all.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:41.586487+00:00 app[web.1]: 
2014-01-09T01:58:43.572097+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_colors.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.572097+00:00 app[web.1]: 
2014-01-09T01:58:43.582294+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_typography.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.582294+00:00 app[web.1]: 
2014-01-09T01:58:43.592417+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_settings.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.592417+00:00 app[web.1]: 
2014-01-09T01:58:43.610116+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_mixins.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.610116+00:00 app[web.1]: 
2014-01-09T01:58:43.662146+00:00 app[web.1]: Warning. Error encountered while saving cache 208d024c3387f3aaad21f7177290d756a4e172da/layout.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.662146+00:00 app[web.1]: 
2014-01-09T01:58:43.747593+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_all.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:43.747593+00:00 app[web.1]: 
2014-01-09T01:58:45.737015+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_colors.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:45.737094+00:00 app[web.1]: 
2014-01-09T01:58:45.752451+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_typography.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:45.752451+00:00 app[web.1]: 
2014-01-09T01:58:45.768499+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_settings.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:45.768499+00:00 app[web.1]: 
2014-01-09T01:58:45.785067+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_mixins.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:45.785067+00:00 app[web.1]: 
2014-01-09T01:58:46.155578+00:00 app[web.1]: Warning. Error encountered while saving cache 208d024c3387f3aaad21f7177290d756a4e172da/typography.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:46.155578+00:00 app[web.1]: 
2014-01-09T01:58:46.160691+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_all.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:46.160691+00:00 app[web.1]: 
2014-01-09T01:58:48.157291+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_colors.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:48.157291+00:00 app[web.1]: 
2014-01-09T01:58:48.166826+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_typography.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:48.166826+00:00 app[web.1]: 
2014-01-09T01:58:48.177115+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_settings.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:48.177115+00:00 app[web.1]: 
2014-01-09T01:58:48.187237+00:00 app[web.1]: Warning. Error encountered while saving cache bb9a85f496dc0a0662c509e77aac0fc26eb7f403/_mixins.scssc: can't dump anonymous class #<Class:0x007f4b441cf7c8>
2014-01-09T01:58:48.187237+00:00 app[web.1]: 
2014-01-09T01:58:57.454779+00:00 app[web.1]: E, [2014-01-09T01:58:57.454527 #2] ERROR -- : worker=1 PID:20 timeout (16s > 15s), killing
2014-01-09T01:58:57.486940+00:00 app[web.1]: E, [2014-01-09T01:58:57.486731 #2] ERROR -- : reaped #<Process::Status: pid 20 SIGKILL (signal 9)> worker=1
2014-01-09T01:58:57.527329+00:00 app[web.1]: I, [2014-01-09T01:58:57.526892 #26]  INFO -- : worker=1 ready
2014-01-09T01:58:57.503162+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path=/styleguide host=blerp.com fwd="76.79.149.70" dyno=web.1 connect=2ms service=16087ms status=503 bytes=0
2014-01-09T02:06:09.089421+00:00 app[web.1]: Started GET "/" for 54.211.164.11 at 2014-01-09 02:06:09 +0000
2014-01-09T02:06:09.091931+00:00 app[web.1]: Processing by WelcomeController#index as HTML
2014-01-09T02:06:09.107444+00:00 app[web.1]: Redirected to http://blerp.com
2014-01-09T02:06:09.108476+00:00 app[web.1]: Filter chain halted as :login_required rendered or redirected
2014-01-09T02:06:09.108674+00:00 app[web.1]: Completed 302 Found in 17ms (ActiveRecord: 0.0ms)
2014-01-09T02:06:09.112484+00:00 heroku[router]: at=info method=GET path=/ host=blerp.com fwd="54.211.164.11" dyno=web.1 connect=1ms service=24ms status=302 bytes=191
2014-01-09T02:06:09.138307+00:00 app[web.1]: Started GET "https://blerp.com/" for 54.211.164.11 at 2014-01-09 02:06:09 +0000
2014-01-09T02:06:09.223289+00:00 app[web.1]: I, [2014-01-09T02:06:09.222927 #23]  INFO -- omniauth: (blerp) Request phase initiated.
2014-01-09T02:06:09.249866+00:00 heroku[router]: at=info method=GET path=https://blerp.com/ host=blerp.com fwd="54.211.164.11" dyno=web.1 connect=2ms service=120ms status=302 bytes=284
```

**Comment by jathayde** [comment]
@chrisgriffin how did you solve this?
