### ISSUE TITLE
Breaks `resque:work`?

### ISSUE THREAD

**Issue by alanhogan** [dewski/kss-rails#8]
```
bundle exec rake resque:work

rake aborted!
No such file to load -- kss/application_controller
```

Thoughts?

**Comment by dewski** [comment]
Could you get me the stack trace for that worker? Also, which version of kss-rails are you using?

**Comment by alanhogan** [comment]
I’m using `kss-rails-alan` (1.0.3), which is based on the `kss-rails` master branch as of two months ago.

Stack trace:

```
>>> bx rake resque:work --trace

** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Execute resque:setup
** Execute resque:preload
rake aborted!
No such file to load -- kss/application_controller
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:317:in `rescue in depend_on'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:312:in `depend_on'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:225:in `require_dependency'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:438:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:438:in `block in eager_load!'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:436:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:436:in `eager_load!'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/application/railties.rb:8:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/application/railties.rb:8:in `all'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/railties-3.2.6/lib/rails/engine.rb:434:in `eager_load!'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/gems/resque-1.20.0/lib/resque/tasks.rb:54:in `block (2 levels) in <top (required)>'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/alanjhogan/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/Users/alanjhogan/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `load'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/bin/ruby_noexec_wrapper:14:in `eval'
/Users/alanjhogan/.rvm/gems/ruby-1.9.3-p194@ifttt-rails3/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => resque:work => resque:preload
```
